### 상품 추가
POST localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPeUtZTEJJdXY4am1hOUZ0eTJNbHpNQzhvenJoNXRDaG15eXBpUlpSNkRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzM0MDc1MTc4LCJleHAiOjE3MzQxNjE1Nzh9.EJjvHy3m9gs2R5Wzf1tVAGTQzCXHrBk1ZQ28N-lY6LI

{
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 10000
    }
  ],
  "name": "나이키 에어포스"
}

### 상품 아이템 추가
POST localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJPeUtZTEJJdXY4am1hOUZ0eTJNbHpNQzhvenJoNXRDaG15eXBpUlpSNkRrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzM0MDc1MTc4LCJleHAiOjE3MzQxNjE1Nzh9.EJjvHy3m9gs2R5Wzf1tVAGTQzCXHrBk1ZQ28N-lY6LI

{
      "productId": 1,
      "count": 1,
      "name": "280",
      "price": 10000
}

